import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import Footer from "@/components/product/Footer";

import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Home",
  // description: "Generated by create next app",
};

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-outfit",
});

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={` ${outfit.variable} antialiased`}>
      {children}
      <Footer />
    </div>
  );
}
