export const productsData = [
  {
    id: 1,
    name: "Smart Watch",
    price: 120,
    img: "https://images.pexels.com/photos/110471/pexels-photo-110471.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Track your fitness and stay connected with notifications.",
    cta: "Buy",
    slug: "/watches",
  },
  {
    id: 2,
    name: "Airpod",
    price: 60,
    img: "https://images.pexels.com/photos/8722142/pexels-photo-8722142.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Ergonomic design with high-precision sensors.",
    cta: "Get",
    slug: "/airpod",
  },
  {
    id: 3,
    name: "Wireless Headphones",
    price: 150,
    img: "https://images.pexels.com/photos/610945/pexels-photo-610945.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "High-quality noise-canceling wireless headphones.",
    cta: "Purchase",
    slug: "/headphone",
  },

  {
    id: 4,
    name: "Gaming Mouse",
    price: 60,
    img: "https://images.pexels.com/photos/2115256/pexels-photo-2115256.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Ergonomic design with high-precision sensors.",
    cta: "Buy",
    slug: "/mouse",
  },
  {
    id: 5,
    name: "Nivea",
    price: 60,
    img: "https://images.pexels.com/photos/18353026/pexels-photo-18353026/free-photo-of-flip-flops-towel-and-a-sunscreen-on-the-beach.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Ergonomic design with high-precision sensors.",
    cta: "Buy",
    slug: "/cream",
  },
  {
    id: 6,
    name: "iMac",
    price: 60,
    img: "https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Ergonomic design with high-precision sensors.",
    cta: "See more",
    slug: "/monitors",
  },
];
